def zakir_name():
    print("    _______________")
    print("                  /")
    print("                 / ")
    print("                /  ")
    print("               /   ")
    print("              /    ")
    print("             /     ")
    print("            /      ")
    print("           /       ")
    print("          /        ")
    print("         /         ")
    print("        /          ")
    print("       /           ")  
    print("      /            ")  
    print("     /             ")
    print("    /              ")
    print("   /               ")
    print("  /                ")
    print(" /                 ")
    print("/                  ")
    print("___________________")
    

